name: flutter_media_notification
version: 1.0.0

author: aliyazdi75 <ma.yazdi75@gmail.com>
description: Flutter Media Notification is a package that you can use it to show you media notification and control streaming media beyond your app.
homepage: https://github.com/aliyazdi75/flutter_media_notification

environment:
  sdk: ">=2.4.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.tarafdari.flutter_media_notification
    pluginClass: FlutterMediaNotificationPlugin